### ISSUE TITLE
Where is the Currying implementation?

### ISSUE THREAD

**Issue by why-not-try-calmer** [JasonShin/fp-core.rs#66]
Currying is a fundamental feature and it's talked about in the README.md but I couldn't find any implementation -- as opposed to a single example -- of it in the actual lib. This looks like a missing feature.

Any plan on adding it?

**Comment by black7375** [comment]
IMO, This crates looks good.
https://crates.io/crates/cutlass

**Comment by wgxh-cli** [comment]
> IMO, This crates looks good. https://crates.io/crates/cutlass

It looks like the library doesn't adapt the `lifetime cycles` of the function parameters.
I'm making wheel recently, I found that currying in Rust is difficult from other languages.

Such as the lifetime cycles of functions, if the parameters used the lifetime bounds, then the closure in function body will throw a error. And the solution to this problem is to add lifetime bounds to the function return type.

It's obviously a terrible thing to fiddle with currying in Rust. But I think there should be a possible solution, although there are also some complex situations under the currying.

BTW, there is my [new wheel](https://github.com/wgxh-cli/ffp.rs)
